'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const base={company:'MoonMail Cosmic Supply Department',orderNumber:'MM-2048',date:'2026-08-03',status:'In transit',customerName:'Jane Doe',address:'123 Main Street, Bend, OR 97701, Planet Earth',currency:'USD',shipping:12,tax:8.8,discount:0,miles:185,tracking:38,theme:'space',paymentMethod:'Galactic Visa ···· 4242',transactionId:'TX-MOON-889103',products:[{name:'Pocket Moon Fragment',description:'Certified lunar souvenir · Silver edition',qty:1,price:89.99},{name:'Zero-Gravity Coffee',description:'Dark orbit roast · 12 capsule pack',qty:2,price:24.99},{name:'Nebula Postcard Set',description:'Five holographic deep-space prints',qty:1,price:19}]};
let state=structuredClone(base),lang=localStorage.getItem('moonmail-lang')||'en',motion=localStorage.getItem('moonmail-motion')!=='off',game;
const tr={en:{paymentConfirmed:'Payment confirmed',headline:'Your cargo is cleared for interstellar delivery.',intro:'Thanks for trusting MoonMail. Your payment is recorded and your shipment is prepared.',items:'Items',miles:'Moon Miles',days:'Earth days',order:'Order',date:'Date',status:'Status',cargo:'Expedition cargo',reward:'Cosmic reward unlocked',rewardDesc:'Free meteor protection included',subtotal:'Subtotal',shipping:'Orbital handling',tax:'Earth atmosphere tax',discount:'Discount',total:'Total paid',paidWith:'Paid with',destination:'Destination',tracking:'Delivery trajectory',confirmed:'Confirmed',orbit:'Orbit',atmosphere:'Atmosphere',delivered:'Delivered',distance:'Distance',speed:'Speed',arrival:'Arrival',verify:'Verify your cosmic purchase'},ro:{paymentConfirmed:'Plată confirmată',headline:'Încărcătura ta este pregătită pentru livrare interstelară.',intro:'Îți mulțumim că ai ales MoonMail. Plata este înregistrată, iar expediția este pregătită.',items:'Produse',miles:'Moon Miles',days:'Zile terestre',order:'Comandă',date:'Data',status:'Status',cargo:'Încărcătura expediției',reward:'Recompensă cosmică deblocată',rewardDesc:'Protecție anti-meteori inclusă',subtotal:'Subtotal',shipping:'Manipulare orbitală',tax:'Taxă atmosferică',discount:'Reducere',total:'Total achitat',paidWith:'Plătit cu',destination:'Destinație',tracking:'Traiectoria livrării',confirmed:'Confirmată',orbit:'Orbită',atmosphere:'Atmosferă',delivered:'Livrată',distance:'Distanță',speed:'Viteză',arrival:'Sosire',verify:'Verifică achiziția cosmică'}};
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function date(v){return new Intl.DateTimeFormat(lang==='ro'?'ro-RO':'en-US',{year:'numeric',month:'long',day:'numeric'}).format(new Date(v+'T12:00:00'))}
function money(v){return state.currency==='LUN'?Number(v).toFixed(2)+' LUN':new Intl.NumberFormat(lang==='ro'?'ro-RO':'en-US',{style:'currency',currency:state.currency}).format(v)}
function sums(){const subtotal=state.products.reduce((a,p)=>a+p.qty*p.price,0),tax=subtotal*state.tax/100;return{subtotal,tax,total:Math.max(0,subtotal+state.shipping+tax-state.discount)}}
function bind(k,v){$$(`[data-bind="${k}"]`).forEach(e=>e.textContent=v)}
function products(){const l=$('#productList'),ed=$('#productEditor');l.innerHTML=ed.innerHTML='';state.products.forEach((p,i)=>{const row=document.createElement('article');row.className='product-row';row.innerHTML=`<div class="product-art">${['◐','☕','✦','⬡'][i%4]}</div><div class="product-copy"><strong>${esc(p.name)}</strong><small>${esc(p.description)}</small><span>${p.qty} × ${money(p.price)}</span></div><div class="product-price">${money(p.qty*p.price)}</div>`;l.append(row);const r=$('#productEditorTemplate').content.firstElementChild.cloneNode(true);$$('input',r).forEach(inp=>{const f=inp.dataset.field;inp.value=p[f];inp.oninput=()=>{p[f]=['qty','price'].includes(f)?Math.max(f==='qty'?1:0,+inp.value||0):inp.value;render(false)}});$('[data-action="remove"]',r).onclick=()=>{if(state.products.length===1)return toast('At least one product');state.products.splice(i,1);render()};ed.append(r)})}
function qr(){const c=$('#qrCanvas'),data=JSON.stringify({order:state.orderNumber,total:sums().total,currency:state.currency});if(window.QRCode?.toCanvas)QRCode.toCanvas(c,data,{width:112,margin:1,color:{dark:'#101426',light:'#fff'}}).catch(()=>{});else{const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,112,112);x.fillStyle='#101426';for(let y=0;y<14;y++)for(let a=0;a<14;a++)if((a*7+y*11)%3===0)x.fillRect(a*8,y*8,7,7)}}
function render(rebuild=true){document.documentElement.dataset.theme=state.theme;bind('orderNumber',state.orderNumber);bind('date',date(state.date));bind('status',state.status);bind('customerName',state.customerName);bind('address',state.address);bind('paymentMethod',state.paymentMethod);bind('transactionId',state.transactionId);$('#itemCount').textContent=state.products.reduce((a,p)=>a+p.qty,0);$('#milesValue').textContent=state.miles;$('#daysValue').textContent=Math.max(1,Math.ceil((100-state.tracking)/11));$('#trackingPercent').textContent=state.tracking+'%';$('#routeFill').style.width=state.tracking+'%';$('#ship').style.left=`calc(${state.tracking}% - 7px)`;$('#distanceValue').textContent=Math.max(0,Math.round(567000*(1-state.tracking/100))).toLocaleString()+' km';$('#verifyId').textContent=`${state.orderNumber}-${state.customerName.split(' ').at(-1).toUpperCase()}`;const s=sums();$('#subtotalValue').textContent=money(s.subtotal);$('#shippingValue').textContent=money(state.shipping);$('#taxValue').textContent=money(s.tax);$('#discountValue').textContent='-'+money(state.discount);$('#totalValue').textContent=money(s.total);if(rebuild)products();qr()}
const fields={companyInput:'company',orderInput:'orderNumber',dateInput:'date',statusInput:'status',customerInput:'customerName',addressInput:'address',currencyInput:'currency',shippingInput:'shipping',taxInput:'tax',discountInput:'discount',milesInput:'miles',trackingInput:'tracking',themeSelect:'theme'};
function sync(){Object.entries(fields).forEach(([id,k])=>$('#'+id).value=state[k])}
function setupFields(){Object.entries(fields).forEach(([id,k])=>{const e=$('#'+id);e.value=state[k];e.oninput=()=>{state[k]=['shipping','tax','discount','miles','tracking'].includes(k)?+e.value||0:e.value;render(k!=='tracking')}})}
function panel(n){$$('.tab').forEach(e=>e.classList.toggle('is-active',e.dataset.panel===n));$$('.panel').forEach(e=>e.classList.remove('is-active'));$('#'+n+'Panel').classList.add('is-active')}
function language(){document.documentElement.lang=lang;$$('[data-i18n]').forEach(e=>e.textContent=tr[lang][e.dataset.i18n]||e.textContent);$('#langBtn').textContent=lang==='en'?'RO':'EN';localStorage.setItem('moonmail-lang',lang);render()}
function history(){const list=$('#historyList'),a=JSON.parse(localStorage.getItem('moonmail-history')||'[]');list.innerHTML=a.length?'':'<p>No saved receipts yet.</p>';a.forEach(r=>{const e=document.createElement('article');e.className='history-item';e.innerHTML=`<div><strong>${esc(r.state.orderNumber)}</strong><small>${new Date(r.at).toLocaleString()} · ${esc(r.state.customerName)}</small></div><button class="soft-btn">Load</button><button class="danger-btn">Delete</button>`;const[b,d]=$$('button',e);b.onclick=()=>{state=structuredClone(r.state);sync();render();panel('preview')};d.onclick=()=>{localStorage.setItem('moonmail-history',JSON.stringify(a.filter(x=>x.id!==r.id)));history()};list.append(e)})}
function save(){const a=JSON.parse(localStorage.getItem('moonmail-history')||'[]');a.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),state:structuredClone(state)});localStorage.setItem('moonmail-history',JSON.stringify(a.slice(0,20)));history();toast('Receipt saved')}
function download(name,content,type){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
async function png(){if(!window.html2canvas)return toast('PNG library unavailable');const c=await html2canvas($('#receipt'),{backgroundColor:null,scale:2});const a=document.createElement('a');a.download=state.orderNumber+'.png';a.href=c.toDataURL();a.click()}
function random(){const names=['Nova Ray','Luna Vega','Orion Vale','Mira Sol'],items=['Comet Compass','Lunar Tea','Asteroid Cookie Box','Nebula Lamp'];state.orderNumber='MM-'+Math.floor(1000+Math.random()*8999);state.customerName=names[Math.floor(Math.random()*names.length)];state.tracking=Math.floor(Math.random()*91);state.miles=Math.floor(80+Math.random()*420);state.products=Array.from({length:2+Math.floor(Math.random()*3)},(_,i)=>({name:items[i%items.length],description:'Limited cosmic collection',qty:1+Math.floor(Math.random()*3),price:+(8+Math.random()*80).toFixed(2)}));sync();render()}
function simulate(){let v=state.tracking;const t=setInterval(()=>{state.tracking=v=Math.min(100,v+2);$('#trackingInput').value=v;render(false);if(v===100){clearInterval(t);state.status='Delivered';$('#statusInput').value='Delivered';render(false);toast('Delivery complete!')}},80)}
function stars(){const c=$('#stars'),x=c.getContext('2d');let s=[];function size(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;s=Array.from({length:Math.min(180,innerWidth/8)},()=>({x:Math.random()*c.width,y:Math.random()*c.height,r:Math.random()*1.6*devicePixelRatio,a:.2+Math.random()*.7,v:.05+Math.random()*.18}))}function draw(){x.clearRect(0,0,c.width,c.height);if(['space','neon'].includes(state.theme))s.forEach(o=>{x.globalAlpha=o.a;x.fillStyle='#fff';x.beginPath();x.arc(o.x,o.y,o.r,0,7);x.fill();if(motion&&(o.y+=o.v*devicePixelRatio)>c.height)o.y=0});x.globalAlpha=1;requestAnimationFrame(draw)}size();addEventListener('resize',size);draw()}
function gameInit(){const c=$('#gameCanvas'),x=c.getContext('2d'),keys=new Set();addEventListener('keydown',e=>keys.add(e.key.toLowerCase()));addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));$('#gameStartBtn').onclick=()=>{game={run:true,score:0,p:{x:360,y:305,w:42,h:22},cargo:[],rocks:[],tick:0};loop()};function hit(a,b){return a.x<b.x+b.r&&a.x+a.w>b.x-b.r&&a.y<b.y+b.r&&a.y+a.h>b.y-b.r}function loop(){if(!game?.run)return;game.tick++;if(game.tick%45===0)game.cargo.push({x:20+Math.random()*720,y:-20,r:9});if(game.tick%70===0)game.rocks.push({x:20+Math.random()*720,y:-25,r:14+Math.random()*8,v:2.5+Math.random()*2});if(keys.has('arrowleft')||keys.has('a'))game.p.x-=6;if(keys.has('arrowright')||keys.has('d'))game.p.x+=6;game.p.x=Math.max(0,Math.min(c.width-game.p.w,game.p.x));game.cargo.forEach(o=>o.y+=2.7);game.rocks.forEach(o=>o.y+=o.v);game.cargo=game.cargo.filter(o=>{if(hit(game.p,o)){game.score+=10;$('#gameScore').textContent='Score: '+game.score;return false}return o.y<c.height});if(game.rocks.some(o=>hit(game.p,o))){game.run=false;toast('Mission ended · '+game.score)}game.rocks=game.rocks.filter(o=>o.y<c.height+30);const g=x.createLinearGradient(0,0,0,c.height);g.addColorStop(0,'#0b1028');g.addColorStop(1,'#171335');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.fillStyle='#fff';for(let i=0;i<50;i++)x.fillRect((i*137+game.tick*.2)%c.width,(i*83)%c.height,1.5,1.5);x.fillStyle='#8b7cff';x.fillRect(game.p.x,game.p.y,game.p.w,game.p.h);x.fillStyle='#7df0cc';x.fillRect(game.p.x+13,game.p.y-8,16,8);game.cargo.forEach(o=>{x.fillStyle='#ffd76a';x.fillRect(o.x-8,o.y-8,16,16)});game.rocks.forEach(o=>{x.fillStyle='#ff718d';x.beginPath();x.arc(o.x,o.y,o.r,0,7);x.fill()});if(game.run)requestAnimationFrame(loop)}}
document.addEventListener('DOMContentLoaded',()=>{setupFields();$$('.tab').forEach(e=>e.onclick=()=>panel(e.dataset.panel));$$('.seg').forEach(e=>e.onclick=()=>{$$('.seg').forEach(b=>b.classList.toggle('is-active',b===e));$('#previewStage').className='preview-stage '+e.dataset.view;$('#inboxMock').hidden=e.dataset.view!=='inbox'});const add=()=>{state.products.push({name:'New cosmic item',description:'Ready for interstellar dispatch',qty:1,price:9.99});render();panel('builder')};$('#addProductBtn').onclick=$('#addProductQuick').onclick=add;$('#saveBtn').onclick=save;$('#shareBtn').onclick=()=>navigator.clipboard.writeText(`MoonMail ${state.orderNumber} · ${money(sums().total)}`).then(()=>toast('Summary copied'));$('#copyOrderBtn').onclick=()=>navigator.clipboard.writeText(state.orderNumber).then(()=>toast('Order copied'));$('#langBtn').onclick=()=>{lang=lang==='en'?'ro':'en';language()};$('#themeBtn').onclick=()=>{const a=['space','earth','mars','neon','thermal'];state.theme=a[(a.indexOf(state.theme)+1)%a.length];sync();render();$('#themeBtn').textContent=state.theme};$('#motionBtn').onclick=()=>{motion=!motion;localStorage.setItem('moonmail-motion',motion?'on':'off');document.documentElement.classList.toggle('reduced-motion',!motion);$('#motionBtn').textContent=motion?'Motion':'Still'};$('#simulateBtn').onclick=simulate;$('#randomizeBtn').onclick=random;$('#pngBtn').onclick=png;$('#printBtn').onclick=print;$('#jsonBtn').onclick=()=>download(state.orderNumber+'.json',JSON.stringify({...state,totals:sums()},null,2),'application/json');$('#htmlBtn').onclick=()=>download(state.orderNumber+'.html','<!doctype html><meta charset="utf-8">'+$('#receipt').outerHTML,'text/html');$('#resetBtn').onclick=()=>{state=structuredClone(base);sync();render();toast('Reset complete')};$('#clearHistoryBtn').onclick=()=>{localStorage.removeItem('moonmail-history');history()};$('#secretLogo').onclick=()=>{state.theme='neon';sync();render();toast('Neon transmission unlocked')};language();history();stars();gameInit();document.documentElement.classList.toggle('reduced-motion',!motion)})